# Generated by Django 6.1 on 2026-08-18 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('last_triggered_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CameraSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source_type', models.CharField(choices=[('webcam', 'Webcam'), ('ip_camera', 'IP camera'), ('upload', 'Uploaded video')], default='webcam', max_length=20)),
                ('location', models.CharField(max_length=160)),
                ('stream_url', models.CharField(blank=True, help_text='Stored for local integrations; never returned by the API.', max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_sources', to='tenants.room')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('person', 'Person detected'), ('bottle', 'Bottle detected'), ('possible_smoke', 'Possible smoke'), ('possible_fire', 'Possible fire'), ('manual', 'Manual report'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('dismissed', 'Dismissed'), ('assigned', 'Assigned')], default='new', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('detected_labels', models.JSONField(blank=True, default=list)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ImageField(blank=True, upload_to='incidents/%Y/%m/')),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('assigned_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='tenants.tenant')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='tenants.room')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='monitoring.camerasource')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/videos/%Y/%m/')),
                ('source_name', models.CharField(default='Uploaded video', max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('frames_processed', models.PositiveIntegerField(default=0)),
                ('incidents_created', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_jobs', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_jobs', to='tenants.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
